### ISSUE TITLE
Remove this repo from distribution

### ISSUE THREAD

**Issue by pllim** [spacetelescope/pywcs#1]
Astropy WCS (http://docs.astropy.org/en/stable/wcs/index.html)?

**Comment by pllim** [comment]
@nden says that this is replaced by Astropy WCS. Any dependency to this needs to go, @jhunkeler .

**Comment by SaOgaz** [comment]
Can we close this? Is it removed from Astroconda?

**Comment by SaOgaz** [comment]
I see the answer is yes, hey @jhunkeler and @rendinam, can we remove this from Astroconda? I'd like to get this closed before I archive this repo.

**Comment by jhunkeler** [comment]
The build for `pywcs` has been disabled for a very long time. Unfortunately we can't delete the package from the channel or it will break older versions of certain packages.

In other words, feel free to archive this repo.

**Comment by pllim** [comment]
>  it will break older versions of certain packages

Do people still use those older packages? Can we stop distributing them? :thinking:

**Comment by SaOgaz** [comment]
Ok, closing this issue now, thanks @jhunkeler!
